-- CONSULTA SQL PARA OBTENÇÃO DOS DADOS DE VENDAS DE PRODUTOS EM CADA LOJA
-- AUTOR: LUCAS LAI BARBOSA

----- TEMPORÁRIA DE VENDAS
DROP TABLE IF EXISTS #BASE_VENDAS
SELECT 
	DISTINCT
	ID_PRODUTO,
	ID_LOJA,
	DATEDIFF(DD, MIN(DATA_COMPRA), MAX(DATA_COMPRA)) AS TEMPO_EM_LOJA,
	SUM(QUANTIDADE_PRODUTO) AS QTD_PRODUTOS_VENDIDOS,
	SUM(TOTAL_PRECO_PRODUTO_RATEADO) AS VALOR_TOTAL_VENDIDO
INTO #BASE_VENDAS	
FROM [CRM].[TRANSACIONAL_VENDA] WITH(NOLOCK) 
WHERE CAST(DATA_COMPRA AS DATE) BETWEEN '2021-06-01' AND '2022-05-31'
	AND ID_PRODUTO IS NOT NULL 
	AND OPERACAO_PRODUTO = 'COMPRA'
GROUP BY
ID_PRODUTO, ID_LOJA

----- TEMPORÁRIA PARA FILTRAR PRODUTOS COM PELO MENOS 10 VENDAS EM 10 LOJAS E QUE FICARAM AO MENOS 30 DIAS NELAS
DROP TABLE IF EXISTS #BASE_PRODUTOS
SELECT 
	DISTINCT ID_PRODUTO,
	COUNT(ID_LOJA) AS 'QTD_LOJAS'
INTO #BASE_PRODUTOS
FROM #BASE_VENDAS
WHERE QTD_PRODUTOS_VENDIDOS >= 10 ---- PRODUTOS COM PELO MENOS 10 VENDAS POR LOJA
	  AND TEMPO_EM_LOJA >= 30 -------- PRODUTOS COM PELO MENOS 30 DIAS ENTRE PRIMEIRA E ÚLTIMA VENDA
GROUP BY ID_PRODUTO
HAVING COUNT(DISTINCT ID_LOJA) >= 10 -- PRODUTOS VENDIDOS EM PELO MENOS 10 LOJAS

----- SELECT FINAL
SELECT 
	V.ID_PRODUTO,
	CP.DEPARTAMENTO,
	CP.MATERIAL_SEGMENTO,
	CP.MATERIAL_SUBSEGMENTO,
	CP.MATERIAL_GRUPO,
	CP.MATERIAL_SUBGRUPO,
	CP.MATERIAL_MARCA,
	CP.MATERIAL_COR,
	V.ID_LOJA,
	L.CIDADE,
	L.UF,
	L.Temp_loja,
	L.Cluster_low_high,
	V.TEMPO_EM_LOJA,
	CAST(V.VALOR_TOTAL_VENDIDO / V.QTD_PRODUTOS_VENDIDOS AS MONEY) AS PRECO_UNIT,
	V.QTD_PRODUTOS_VENDIDOS,
	CAST(V.VALOR_TOTAL_VENDIDO AS MONEY) AS VALOR_TOTAL_VENDIDO
FROM #BASE_VENDAS V
	INNER JOIN #BASE_PRODUTOS P ON V.ID_PRODUTO = P.ID_PRODUTO
	INNER JOIN CRM.CATALOGO_PRODUTOS CP ON CP.MATERIAL_CODIGO = P.ID_PRODUTO
	LEFT JOIN CRM.CADASTRO_LOJA L ON L.CENTRO = V.ID_LOJA
WHERE 
	CP.DEPARTAMENTO <> 'ACESSORIOS'
	AND V.QTD_PRODUTOS_VENDIDOS >= 10 ---- COMBINAÇÃO DE PRODUTO E LOJA COM PELO MENOS 10 VENDAS
	AND V.TEMPO_EM_LOJA >= 30 ------------ COMBINAÇÃO DE PRODUTO E LOJA COM PELO MENOS 30 DIAS ENTRE PRIMEIRA E ÚLTIMA VENDA
ORDER BY 2,1